version: '2'
services: 
  database: 
    image: mysql:5.7
    volumes: 
      - dbdata:/var/lib/mysql
    environment: 
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_PORT=3306"
    ports: 
      - 3306:3306

  app:
    image: felipe/laravelapp
    working_dir: /var/www
    volumes: 
      - /var/www/storage
    env_file: '.env'
    environment: 
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "REDIS_HOST=cache"
    links: 
      - database
    depends_on: 
      - database

  web:
    image: jakelima18/laravel-web
    ports: 
      - 80:80
    links: 
      - app

  cache: 
    image: redis:3.0-alpine

volumes: 
  dbdata:
